version: '3.9'

services:
  dashboard:
    container_name: dashboard
    build:
      context: .
    command: bash -c "python dashboard/manage.py migrate && python dashboard/manage.py runserver 0.0.0.0:8000"
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
  bot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - .env