version: '3.1'

services:

  dashboard:
    container_name: dashboard
    build:
      context: .
    command: bash -c "python django_app.py migrate && python django_app.py runserver 0.0.0.0:8080"
    restart: always
    networks: 
      - work_bot
    ports:
      - 8080:8080
    env_file:
      - .env
  bot:
    container_name: bot
    build:
      context: .
    command: python app.py
    restart: always
    env_file:
      - .env
    networks:
      - bot
networks:
  bot:
    driver: bridge
